# Site settings
title: 6th Street Marketing
email: bbordofsky@6thstreetmarketing.com
description: > # this means to ignore newlines until "baseurl:"
  Fintech marketing solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

#Google Analytics
google_analytics: UA—XXXXXXXX-X 

# Build settings
markdown: kramdown
